theme: jekyll-theme-leap-day
title: Tasmota-Plus
description: Tasmota, plus features for IT Professionals
show_downloads: false 
defaults:
  - scope:
      path: ""
    values:
      layout: default

